### PR TITLE
feat: add a community page

### PR DESCRIPTION
**Pull request by zkochan**

### CODE REVIEW

**Comment by juanpicado** [comment]
I could continue this if you describe me what you want to achieve.

**Comment by zkochan** [comment]
We have this community page: https://pnpm.io/community

I wanted to divide into several subpages. Like `/community/artices`, `/community/tools`, etc

**Comment by hunter2009** [comment]
It's a good idea, I found the structure  of pnpm official website structure is clear. Some pages need to divied into  subpages like what [react doc](https://devdocs.io/react/) did.
image

**Comment by olrtg** [comment]
Hi guys! please take a look at the new PR #214

**Pull request closed without merging**
