### PR TITLE
Merge  source from pt-br => source (original)

### PR DESCRIPTION
**Pull request by rmaycon**

### CODE REVIEW

**Comment by rmaycon** [comment]
corrected some errors caused by the translator, some tags, `pnpm install`, instead of the original file. the titles of some of the pages were also buggy, and the code blocks were also having problems, too, they were translated, function => função.

**Comment by rmaycon** [comment]
I do not speak English, I use google translate this to do the translation of the codumentação and for the messages here.

**Comment by zkochan** [comment]
I will add your translations to this system: https://crowdin.com/project/pnpm

Please do your edits there. Translations should be downloaded from crowdin

**Comment by rmaycon** [comment]
> I will add your translations to this system: https://crowdin.com/project/pnpm
> 
> Please do your edits there. Translations should be downloaded from crowdin

mas teria como você adicionar estas correções, do pullrequest? so mudariam algumas coisas que eu não tinha corrigido antes ....

**Comment by zkochan** [comment]
there are too many conflicts. Your fixes should be done on top of the current "source" branch

**Comment by rmaycon** [comment]
>there are too many conflicts. Your fixes should be done on top of the current "source" branch


Você quis dizer: ok, vou corrigir esses erro e fazer uma novo pull request
58/5000
Okay, I'm going to fix these errors and make a new pull request

**Comment by rmaycon** [comment]
> there are too many conflicts. Your fixes should be done on top of the current "source" branch


260/5000
would you like to remove the translation files in translated_docs / en-GB and i18n / en-BR.json? Then I would do a new pull request with the new translated files. the conflict of .gitignore no problem I solve here, putting the original file back.

**Comment by zkochan** [comment]
I reverted the commits. You can try again

**Comment by rmaycon** [comment]
> I reverted the commits. You can try again

It worked! Thank you! waiting for updates ....

**Comment by zkochan** [comment]
I will update the site tomorrow

**Pull request closed without merging**
