### PR TITLE
Feat/docs

### PR DESCRIPTION
**Pull request by samerela**
Description: Moving **docs/** file from [pnpm-site](https://github.com/deadcoder0904/pnpm-site)
repo to [pnpm.github.io](https://github.com/pnpm/pnpm.github.io) repo. Plus adding a docs button in the website.
Issue Reference: [#939](https://github.com/pnpm/pnpm/issues/939)
Issue Repo: [pnpm/pnpm](https://github.com/pnpm/pnpm)

### CODE REVIEW

**Comment by samerela** [comment]
oops.. sorry about that! Now is fixed!

**Comment by zkochan** [comment]
Doesn't seem to work. I tested it with `live-server`. Install it globally and then run `live-server` in the repo root. When you click on docs, a 404 error opens instead of the docs page

**Comment by samerela** [comment]
I think that because the **docs/** directory hasn't been created yet in the master branch in pnpm/pnpm.github.io repo. So I think in order for it to work, this pull request needs to be merged into master branch in pnpm/pnpm.github.io repo. Then when the button is clicked, the URI specified in index.html will be able to locate the directory.

**Comment by zkochan** [comment]
I used gitbook, it was easier to configure than docute https://pnpm.js.org/docs/

**Pull request closed without merging**
