### PR TITLE
Troubleshoot cyclic dependencies (#3569)

### PR DESCRIPTION
**Pull request by javier-garcia-meteologica**
Helps users troubleshoot cyclic dependencies

### CODE REVIEW

**Comment by zkochan** [comment]
it might make more sense to put it to the workspace page.

**Comment by javier-garcia-meteologica** [comment]
Done

**Review by zkochan — COMMENTED** [review]
This change should be copied to https://github.com/pnpm/pnpm.github.io/blob/main/versioned_docs/version-6.x/workspaces.md as well

**Comment by javier-garcia-meteologica** [comment]
I just copied the new troubleshooting section to versioned_docs/version-6.x

**Pull request merged**
