### PR TITLE
DOCS: How to quickly resolve missing deps

### PR DESCRIPTION
**Pull request by o-alexandrov**
## Commits

- ADDED: easiest solution for missing deps

### CODE REVIEW

**Comment by zkochan** [comment]
why to optional dependencies, not prod dependencies? Both will work

**Comment by o-alexandrov** [comment]
Thank you for a fast reply. That's cause setting it in `optionalDependencies` you can ensure that you don't mess up other devs' set ups.

Some people tend to use the `--production` flag when they run `npm i --production`.
IMHO, our use case might affect their workflow, how do you think?

**Comment by o-alexandrov** [comment]
@zkochan 
I would suggest not to do so, because there are cases that a missing dependency is a dependency of a devDependency.
Therefore, you would be installing an unnecessary dependency in a production environment.

Please let me know your final decision and I will add what you would like.

**Comment by zkochan** [comment]
I see, but optionalDependencies will be installed in prod as well, so it doesn't really make a difference

**Comment by o-alexandrov** [comment]
You would be able to avoid them in prod by running:
`npm i -production --no-optional`

**Comment by zkochan** [comment]
but the `--no-optional` will also skip optional deps of subdependencies. So I think a better solution would be to save the new dependency with the same type as the type of the dependency that misses it. So if `iterall` is required by a dev dep, install it as a dev dep. If it is required by an optional dep, install it as an optional dep, etc.

**Comment by o-alexandrov** [comment]
Before starting to use `pnpm` today... 😆 

I used to have an alias:
`ni = npm i --no-optional`

You can safely ignore them as they are unrelated to a working state of a module.

**Comment by zkochan** [comment]
Optional dependencies may improve things on some OS. I don't think we have to suggest developers to run pnpm with `--no-optional` because it looks like a limitation of pnpm

**Comment by o-alexandrov** [comment]
Okay, please edit the changes how you see they would fit better.
I agree that you know better this community and I would happily follow your decision :)

**Pull request merged**
